url: "http://www.tomchristie.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/testing" # the subpath of your site, e.g. /blog
title: "Encode" # the name of your site, e.g. ACME Corp.

exclude:
  - README.md

plugins:
  - jekyll-feed

feed:
  path: feeds/articles.rss
